### PR TITLE
make spec compliant.  created/modified must only be precise to the mi…

### PR DESCRIPTION
**Pull request by jmgnc**
…llisecond

per: https://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709274

## Last Updated Time Change

Before submitting the pull request, please update the `last_updated` on https://github.com/oasis-open/cti-documentation/blob/general_refinement/_config.yml#L16

### CODE REVIEW

**Comment by jmgnc** [comment]
looks like the last update time change template needs to be changed because _config.yml says:
```
# DO NOT MODIFY THE `last_updated` date. It should be updated automatically
# by the git pre-push hook.
```

**Comment by gtback** [comment]
Thanks, @jmgnc. Have you been able to sign the CLA yet? 

This is arguably minor enough that it may not be necessary.

**Comment by jmgnc** [comment]
No, I have not been able to sign the CLA.  In reading the CLA, it appears that any/all contributions to open repos (i.e. github) are required to be via CLA (which means that as a TC, we CANNOT have any TC material in github), which IMO is a major problem and should be fixed.  I'll bring it up w/ others.

Here's how to find all the files that have this issue if you'd like to recreate them:
```
egrep -lr '(created|modified).*\.[0-9][0-9][0-9][0-9][0-9][0-9]Z' .
```

and if you're familar w/ vi, you can just do something like:
```
vi `egrep -lr '(created|modified).*\.[0-9][0-9][0-9][0-9][0-9][0-9]Z' .`
```

and cycle through all the files.

**Comment by gtback** [comment]
The Open Repo guidelines require that any "substantive" contributions be made subject to the CLA. "Substantive" is determined by the maintainer(s) of the repo, which is why I said it *may* not be needed. 

> which means that as a TC, we CANNOT have any TC material in github

Can you clarify what you mean?

**Comment by jmgnc** [comment]
My comment is that cti-documentation being in github (and from my understanding, therefor covered by CLA), though IMO should be a TC work product, is covered by CLA instead of by the TC contributors guidelines.   Maybe is there a different type of github repo that we can have that is open for TC members to contribute to w/o using a CLA?

**Comment by gtback** [comment]
Ahh, that makes more sense, @jmgnc.

The `cti-documentation` repo is an [OASIS TC Open Repository](https://www.oasis-open.org/resources/open-repositories/), which means it is covered by CLA instead of the TC's standard IPR rules. Open Repositories (and this repo) **existed before** [Repositories for TC Members' Chartered Work](https://github.com/oasis-tcs/), which is arguably where this type of content should go (and would make it easier for you to contribute). It would be up to the TC (or anyone in it) to propose a new "Chartered Repo", and then decide how/if to migrate content and redirect people to the new location. I would be supportive of this change (though we should probably discuss it somewhere other than this GitHub issue 😝 ).

cc: @robincover

**Comment by JasonKeirstead** [comment]
Can't we just move the documentation to a TCS one, seems pretty straight forward...

**Comment by gtback** [comment]
@JasonKeirstead Besides the fact that the URLs would change, I don't see a problem.

**Pull request closed without merging**
