### PR TITLE
pre-push Git Hook update

### PR DESCRIPTION
**Pull request by Bojak4616**
Takes care of #45. After discussion using the pre-commit library would have been a lot more overhead than was necessary for the scope of this update.

### CODE REVIEW

**Comment by gtback** [comment]
I've been playing around with this a bit (as you can tell by all the trivial commits). One thing I'm still seeing is that the new commit doesn't actually get pushed along with the originally-intended commits; I had to "git push" twice in order to get the single commit (https://github.com/oasis-open/cti-documentation/pull/46/commits/a4fdb89c76850be62646bec4d4591ae7b7472740) to appear in this PR. I have another local, un-pushed commit for the second time I ran `git push`.

**Review by gtback — CHANGES_REQUESTED** [review]
Need to figure out how to get the hook to actually push the new commit.

**Comment by SecurityDozo** [comment]
Hmm that's interesting. I'm not able to reproduce that bug locally. Here is what it looks like on my end on a test repo. From the git log you can see both getting pushed. Any ideas on what could cause the disparity?

git pre-push example

**Comment by gtback** [comment]
> From the git log you can see both getting pushed.

Not necessarily. That's showing the log of your local branch. Try `git log origin/master` to see. 

For comparison, here's what my log looks like after running `git push` for the *second* time. note that I have two commits generated by the hook, but only one is pushed (my git client also shows branch names, which makes it more readable).

```
commit 80b6dd26c1180fb2ebbaa9ae57b0173af977ed74 (HEAD -> pre-push-hook)
Author: Greg Back <gback@mitre.org>
Date:   Tue Nov 7 22:48:42 2017 +0000

    Git Hook: Updated 'last_updated' time

commit a4fdb89c76850be62646bec4d4591ae7b7472740 (origin/pre-push-hook)
Author: Greg Back <gback@mitre.org>
Date:   Tue Nov 7 22:48:21 2017 +0000

    Git Hook: Updated 'last_updated' time

commit f1981d72d711ff5c05795f3b50af9cd1c42df644
Author: Greg Back <gback@mitre.org>
Date:   Tue Nov 7 22:48:17 2017 +0000

    Make hook executable
```

**Comment by gtback** [comment]
Actually, it's possible to see without running `git log` again. What was pushed to master was `e2f15db..89f6e8c`, which includes the "added test" commit but not the commit generated by the hook.

**Comment by SecurityDozo** [comment]
@gtback When you get a chance can you test out these new changes (e81104c)? I chose option 2 from [this stackoverflow post,](https://stackoverflow.com/questions/21334493/git-commit-in-pre-push-hook) which rejects the push but adds a commit with the updated date. Once another push is done, all changes, including the updated time, are pushed.

**Review by gtback — APPROVED** [review]

**Comment by gtback** [comment]
Looking good! Exactly how I expect it to work 😁

**Pull request merged**
